//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.IdentityModule.Application.Dtos.PortalPageDefinition
{
    public record PortalPageDefinitionDto
    {
        public string Key { get; init; }
        public string ModuleName { get; init; }
        public string ModelName { get; init; }
        public PageActionType PageAction { get; init; }
        public string PagePath { get; init; }
    }
}