SELECT PA.[NAME] AS ATTRIBUTE_NAME,
	PAV.[VALUE] 
FROM [PRODUCT_ATTRIBUTE_VALUES] PAV 
	INNER JOIN [PRODUCT_ATTRIBUTES] PA 
			ON PAV.[ATTRIBUTE_ID] = PA.[ID] 
WHERE PAV.[IsDeleted] = 0 
	AND PA.[IsDeleted] = 0 
	AND PAV.[PRODUCT_ID] = @PRM_PRODUCT_ATTRIBUTE_VALUES_PRODUCT_ID 
	AND PAV.[ATTRIBUTE_ID] = @PRM_PRODUCT_ATTRIBUTE_VALUES_ATTRIBUTE_ID 
	AND PA.[ID] = @PRM_PRODUCT_ATTRIBUTES_ID 
ORDER BY 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 