SELECT PAV.[ID], PAV.[ATTRIBUTE_ID], PAV.[VALUE] 
FROM [PRODUCT_ATTRIBUTE_VALUES] PAV 
WHERE PAV.[IsDeleted] = 0 
	AND PAV.[PRODUCT_ID] = @PRM_PRODUCT_ATTRIBUTE_VALUE_PRODUCT_ID 
ORDER BY PAV.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 