SELECT AW.[ID], AW.[AUCTION_ID] 
FROM [AUCTION_WATCHLISTS] AW 
WHERE AW.[IsDeleted] = 0 
	AND AW.[USER_ID] = @PRM_AUCTION_WATCHLIST_USER_ID 
ORDER BY AW.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 