SELECT AW.[USER_ID] 
FROM [AUCTION_WATCHLISTS] AW 
WHERE AW.[IsDeleted] = 0 
	AND AW.[AUCTION_ID] = @PRM_AUCTION_WATCHLIST_AUCTION_ID 
ORDER BY 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 