SELECT CASE WHEN EXISTS (
SELECT 1 
FROM [AUCTION_WATCHLISTS] AW 
WHERE AW.[IsDeleted] = 0 
	AND AW.[AUCTION_ID] = @PRM_AUCTION_WATCHLIST_AUCTION_ID 
	AND AW.[USER_ID] = @PRM_AUCTION_WATCHLIST_USER_ID ) THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT) END