SELECT B.[ID], B.[AUCTION_ID], B.[BID_AMOUNT], B.[STATUS] 
FROM [BIDS] B 
WHERE B.[IsDeleted] = 0 
	AND B.[BIDDER_ID] = @PRM_BID_BIDDER_ID 
ORDER BY B.[BID_TIME] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 