SELECT B.[ID], B.[BIDDER_ID], B.[BID_AMOUNT], B.[BID_TIME] 
FROM [BIDS] B 
WHERE B.[IsDeleted] = 0 
	AND B.[AUCTION_ID] = @PRM_BID_AUCTION_ID 
ORDER BY B.[BID_AMOUNT] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 