//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Dtos.Order;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.OrderManagementModule.Application.Mappings
{
    public static class OrderMappings
    {
        public static List<OrderDto> ToDto(this IEnumerable<Order> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static OrderDto ToDto(this Order model)
        {
            return new OrderDto
            {
                Id = model.Id,
                OrderNumber = model.OrderNumber,
                CustomerId = model.CustomerId,
                Status = model.Status,
                TotalAmount = model.TotalAmount,
                ShippingAddressId = model.ShippingAddressId,
                BillingAddressId = model.BillingAddressId,
                ShippingMethodId = model.ShippingMethodId,
                PaymentId = model.PaymentId,
                CreatedDate = model.CreatedDate,
                UpdatedDate = model.UpdatedDate
            };
        }

        public static Order ToEntity(this OrderDto model)
        {
            return new Order
            {
                Id = model.Id,
                OrderNumber = model.OrderNumber,
                CustomerId = model.CustomerId,
                Status = model.Status,
                TotalAmount = model.TotalAmount,
                ShippingAddressId = model.ShippingAddressId,
                BillingAddressId = model.BillingAddressId,
                ShippingMethodId = model.ShippingMethodId,
                PaymentId = model.PaymentId,
                CreatedDate = model.CreatedDate,
                UpdatedDate = model.UpdatedDate
            };
        }
    }
}