//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Dtos.OrderNote;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.OrderManagementModule.Application.Mappings
{
    public static class OrderNoteMappings
    {
        public static List<OrderNoteDto> ToDto(this IEnumerable<OrderNote> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static OrderNoteDto ToDto(this OrderNote model)
        {
            return new OrderNoteDto
            {
                Id = model.Id,
                OrderId = model.OrderId,
                Note = model.Note,
                IsCustomerVisible = model.IsCustomerVisible,
                CreatedByUserId = model.CreatedByUserId,
                CreatedDate = model.CreatedDate
            };
        }

        public static OrderNote ToEntity(this OrderNoteDto model)
        {
            return new OrderNote
            {
                Id = model.Id,
                OrderId = model.OrderId,
                Note = model.Note,
                IsCustomerVisible = model.IsCustomerVisible,
                CreatedByUserId = model.CreatedByUserId,
                CreatedDate = model.CreatedDate
            };
        }
    }
}