//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Dtos.ShippingMethod;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.OrderManagementModule.Application.Mappings
{
    public static class ShippingMethodMappings
    {
        public static List<ShippingMethodDto> ToDto(this IEnumerable<ShippingMethod> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ShippingMethodDto ToDto(this ShippingMethod model)
        {
            return new ShippingMethodDto
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Cost = model.Cost,
                IsActive = model.IsActive
            };
        }

        public static ShippingMethod ToEntity(this ShippingMethodDto model)
        {
            return new ShippingMethod
            {
                Id = model.Id,
                Name = model.Name,
                Description = model.Description,
                Cost = model.Cost,
                IsActive = model.IsActive
            };
        }
    }
}