SELECT OI.[ID], OI.[PRODUCT_ID], OI.[PRODUCT_NAME], OI.[SKU], OI.[QUANTITY], OI.[UNIT_PRICE] 
FROM [ORDER_ITEMS] OI 
WHERE OI.[IsDeleted] = 0 
	AND OI.[ORDER_ID] = @PRM_ORDER_ITEM_ORDER_ID 
ORDER BY OI.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 