//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Dtos.AuctionItem;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Mappings
{
    public static class AuctionItemMappings
    {
        public static List<AuctionItemDto> ToDto(this IEnumerable<AuctionItem> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AuctionItemDto ToDto(this AuctionItem model)
        {
            return new AuctionItemDto
            {
                Id = model.Id,
                ProductId = model.ProductId,
                Name = model.Name,
                Description = model.Description,
                Condition = model.Condition,
                OwnerId = model.OwnerId,
                IsAvailable = model.IsAvailable
            };
        }

        public static AuctionItem ToEntity(this AuctionItemDto model)
        {
            return new AuctionItem
            {
                Id = model.Id,
                ProductId = model.ProductId,
                Name = model.Name,
                Description = model.Description,
                Condition = model.Condition,
                OwnerId = model.OwnerId,
                IsAvailable = model.IsAvailable
            };
        }
    }
}