//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Dtos.BidIncrementRule;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Mappings
{
    public static class BidIncrementRuleMappings
    {
        public static List<BidIncrementRuleDto> ToDto(this IEnumerable<BidIncrementRule> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static BidIncrementRuleDto ToDto(this BidIncrementRule model)
        {
            return new BidIncrementRuleDto
            {
                Id = model.Id,
                PriceFrom = model.PriceFrom,
                PriceTo = model.PriceTo,
                IncrementAmount = model.IncrementAmount,
                IsActive = model.IsActive
            };
        }

        public static BidIncrementRule ToEntity(this BidIncrementRuleDto model)
        {
            return new BidIncrementRule
            {
                Id = model.Id,
                PriceFrom = model.PriceFrom,
                PriceTo = model.PriceTo,
                IncrementAmount = model.IncrementAmount,
                IsActive = model.IsActive
            };
        }
    }
}