// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickCode.MyecommerceDemo.IdentityModule.Persistence.Contexts;

#nullable disable

namespace QuickCode.MyecommerceDemo.IdentityModule.Persistence.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260406231628_AutoMigration_20260406_231451_127")]
    partial class AutoMigration_20260406_231451_127
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.ApiMethodAccessGrant", b =>
                {
                    b.Property<string>("PermissionGroupName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PermissionGroupName");

                    b.Property<string>("ApiMethodDefinitionKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ApiMethodDefinitionKey");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsActive");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("'System'");

                    b.HasKey("PermissionGroupName", "ApiMethodDefinitionKey");

                    b.HasIndex("ApiMethodDefinitionKey");

                    b.ToTable("ApiMethodAccessGrants");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.ApiMethodDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Key");

                    b.Property<string>("ControllerName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ControllerName");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("HttpMethod");

                    b.Property<string>("MethodName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("MethodName");

                    b.Property<string>("ModelName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ModelName");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ModuleName");

                    b.Property<string>("UrlPath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("UrlPath");

                    b.HasKey("Key");

                    b.HasIndex("ModuleName");

                    b.HasIndex("ModelName", "ModuleName");

                    b.ToTable("ApiMethodDefinitions");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NormalizedName");

                    b.HasKey("Id");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClaimType");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClaimValue");

                    b.Property<string>("RoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LastName");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NormalizedEmail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NormalizedUserName");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PermissionGroupName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PermissionGroupName");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("PermissionGroupName");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClaimType");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ClaimValue");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LoginProvider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ProviderKey");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.Property<string>("RoleId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LoginProvider");

                    b.Property<string>("Name")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Name");

                    b.Property<string>("Value")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.HasKey("UserId");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ACTION");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGE_SUMMARY");

                    b.Property<string>("ChangedColumns")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGED_COLUMNS");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CORRELATION_ID");

                    b.Property<string>("EntityId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_NAME");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("HASH");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<bool>("IsChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_CHANGED");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_SUCCESS");

                    b.Property<string>("NewValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NEW_VALUES");

                    b.Property<string>("OldValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OLD_VALUES");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("USER_AGENT");

                    b.Property<string>("UserGroup")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_GROUP");

                    b.Property<string>("UserId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("UserName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("AUDIT_LOGS");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.ColumnType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("IconCode")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("IconCode");

                    b.Property<string>("IosComponentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("IosComponentName");

                    b.Property<string>("IosType")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("IosType");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("TypeName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TypeName");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("ColumnTypes");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.KafkaEvent", b =>
                {
                    b.Property<string>("TopicName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("TopicName");

                    b.Property<string>("ApiMethodDefinitionKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ApiMethodDefinitionKey");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsActive");

                    b.HasKey("TopicName");

                    b.HasIndex("ApiMethodDefinitionKey");

                    b.ToTable("KafkaEvents");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Model", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Name");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ModuleName");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.HasKey("Name", "ModuleName");

                    b.HasIndex("ModuleName");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Module", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Name");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.HasKey("Name");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PermissionGroup", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Name");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.HasKey("Name");

                    b.ToTable("PermissionGroups");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PortalMenu", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Key");

                    b.Property<string>("ActionName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ActionName");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Name");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int")
                        .HasColumnName("OrderNo");

                    b.Property<string>("ParentName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ParentName");

                    b.Property<string>("Text")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Text");

                    b.Property<string>("Tooltip")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Tooltip");

                    b.HasKey("Key");

                    b.ToTable("PortalMenus");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PortalPageAccessGrant", b =>
                {
                    b.Property<string>("PermissionGroupName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PermissionGroupName");

                    b.Property<string>("PortalPageDefinitionKey")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PortalPageDefinitionKey");

                    b.Property<string>("PageAction")
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PageAction");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsActive");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("'System'");

                    b.HasKey("PermissionGroupName", "PortalPageDefinitionKey", "PageAction");

                    b.HasIndex("PortalPageDefinitionKey");

                    b.ToTable("PortalPageAccessGrants");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PortalPageDefinition", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Key");

                    b.Property<string>("ModelName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ModelName");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ModuleName");

                    b.Property<string>("PageAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PageAction");

                    b.Property<string>("PagePath")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("PagePath");

                    b.HasKey("Key");

                    b.HasIndex("ModuleName");

                    b.HasIndex("ModelName", "ModuleName");

                    b.ToTable("PortalPageDefinitions");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiryDate");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsRevoked");

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Token");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.TableComboboxSetting", b =>
                {
                    b.Property<string>("TableName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("TableName");

                    b.Property<string>("IdColumn")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("IdColumn");

                    b.Property<string>("StringFormat")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StringFormat");

                    b.Property<string>("TextColumns")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TextColumns");

                    b.HasKey("TableName");

                    b.ToTable("TableComboboxSettings");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.TopicWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("KafkaEventsTopicName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("KafkaEventsTopicName");

                    b.Property<string>("WorkflowContent")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WorkflowContent");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("KafkaEventsTopicName");

                    b.ToTable("TopicWorkflows");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.ApiMethodAccessGrant", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.ApiMethodDefinition", "ApiMethodDefinition")
                        .WithMany("ApiMethodAccessGrants")
                        .HasForeignKey("ApiMethodDefinitionKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("ApiMethodAccessGrants")
                        .HasForeignKey("PermissionGroupName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiMethodDefinition");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.ApiMethodDefinition", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Module", "Module")
                        .WithMany("ApiMethodDefinitions")
                        .HasForeignKey("ModuleName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Model", "Model")
                        .WithMany("ApiMethodDefinitions")
                        .HasForeignKey("ModelName", "ModuleName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Model");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetRoleClaim", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetRole", "AspNetRole")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AspNetRole");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUser", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("AspNetUsers")
                        .HasForeignKey("PermissionGroupName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUserClaim", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUserLogin", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUserRole", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetRole", "AspNetRole")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AspNetRole");

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUserToken", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUser", "AspNetUser")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.KafkaEvent", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.ApiMethodDefinition", "ApiMethodDefinition")
                        .WithMany("KafkaEvents")
                        .HasForeignKey("ApiMethodDefinitionKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApiMethodDefinition");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Model", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Module", "Module")
                        .WithMany("Models")
                        .HasForeignKey("ModuleName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PortalPageAccessGrant", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PermissionGroup", "PermissionGroup")
                        .WithMany("PortalPageAccessGrants")
                        .HasForeignKey("PermissionGroupName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PortalPageDefinition", "PortalPageDefinition")
                        .WithMany("PortalPageAccessGrants")
                        .HasForeignKey("PortalPageDefinitionKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PermissionGroup");

                    b.Navigation("PortalPageDefinition");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PortalPageDefinition", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Module", "Module")
                        .WithMany("PortalPageDefinitions")
                        .HasForeignKey("ModuleName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Model", "Model")
                        .WithMany("PortalPageDefinitions")
                        .HasForeignKey("ModelName", "ModuleName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Model");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUser", "AspNetUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AspNetUser");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.TopicWorkflow", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.KafkaEvent", "KafkaEvent")
                        .WithMany("TopicWorkflows")
                        .HasForeignKey("KafkaEventsTopicName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KafkaEvent");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.ApiMethodDefinition", b =>
                {
                    b.Navigation("ApiMethodAccessGrants");

                    b.Navigation("KafkaEvents");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");

                    b.Navigation("AspNetUserRoles");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserRoles");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.KafkaEvent", b =>
                {
                    b.Navigation("TopicWorkflows");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Model", b =>
                {
                    b.Navigation("ApiMethodDefinitions");

                    b.Navigation("PortalPageDefinitions");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.Module", b =>
                {
                    b.Navigation("ApiMethodDefinitions");

                    b.Navigation("Models");

                    b.Navigation("PortalPageDefinitions");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PermissionGroup", b =>
                {
                    b.Navigation("ApiMethodAccessGrants");

                    b.Navigation("AspNetUsers");

                    b.Navigation("PortalPageAccessGrants");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities.PortalPageDefinition", b =>
                {
                    b.Navigation("PortalPageAccessGrants");
                });
#pragma warning restore 612, 618
        }
    }
}
