//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Domain.Entities;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.MyecommerceDemo.Common;
using QuickCode.MyecommerceDemo.Common.Extensions;
using QuickCode.MyecommerceDemo.Common.Helpers;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Persistence.Contexts;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Dtos.ProductReview;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Mappings;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Persistence.Sql;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.ProductCatalogModule.Persistence.Repositories
{
    public partial class ProductReviewRepository : BaseRepository, IProductReviewRepository
    {
        public async Task<RepoResponse<List<GetByProductIdResponseDto>>> GetByProductIdAsync(int productReviewProductId, bool productReviewIsApproved, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByProductId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByProductIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ProductReview.Query.GetByProductId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRODUCT_REVIEW_PRODUCT_ID = productReviewProductId,
                        PRM_PRODUCT_REVIEW_IS_APPROVED = productReviewIsApproved,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByProductIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ProductReview");
                }
            });
        }

        public async Task<RepoResponse<List<GetPendingApprovalResponseDto>>> GetPendingApprovalAsync(bool productReviewIsApproved, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetPendingApproval", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetPendingApprovalResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ProductReview.Query.GetPendingApproval);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRODUCT_REVIEW_IS_APPROVED = productReviewIsApproved,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetPendingApprovalResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ProductReview");
                }
            });
        }

        public async Task<RepoResponse<List<GetCustomerReviewsResponseDto>>> GetCustomerReviewsAsync(int productReviewCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetCustomerReviews", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetCustomerReviewsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.ProductReview.Query.GetCustomerReviews);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_PRODUCT_REVIEW_CUSTOMER_ID = productReviewCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetCustomerReviewsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in ProductReview");
                }
            });
        }

        public async Task<RepoResponse<GetAverageRatingResponseDto>> GetAverageRatingAsync(int productReviewProductId, bool productReviewIsApproved)
        {
            return await ExecuteWithExceptionHandling("GetAverageRating", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.ProductReview.Query.GetAverageRating);
                var parameters = new
                {
                    PRM_PRODUCT_REVIEW_PRODUCT_ID = productReviewProductId,
                    PRM_PRODUCT_REVIEW_IS_APPROVED = productReviewIsApproved
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetAverageRatingResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in ProductReview");
            });
        }
    }
}