//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Dtos.AuctionSettlement;
using System.Threading.Tasks;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Interfaces.Repositories
{
    public partial interface IAuctionSettlementRepository : IBaseRepository<AuctionSettlementDto>
    {
        Task<RepoResponse<AuctionSettlementDto>> GetByPkAsync(int id);
        Task<RepoResponse<GetByAuctionIdResponseDto>> GetByAuctionIdAsync(int auctionSettlementAuctionId);
        Task<RepoResponse<List<GetOutstandingPaymentsResponseDto>>> GetOutstandingPaymentsAsync(bool auctionSettlementIsPaid, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> MarkAsPaidAsync(int auctionSettlementId, MarkAsPaidRequestDto updateRequest);
    }
}