//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Dtos.AuctionWatchlist;
using System.Threading.Tasks;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Interfaces.Repositories
{
    public partial interface IAuctionWatchlistRepository : IBaseRepository<AuctionWatchlistDto>
    {
        Task<RepoResponse<AuctionWatchlistDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByUserIdResponseDto>>> GetByUserIdAsync(int auctionWatchlistUserId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetWatchersByAuctionResponseDto>>> GetWatchersByAuctionAsync(int auctionWatchlistAuctionId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<bool>> IsWatchingAsync(int auctionWatchlistAuctionId, int auctionWatchlistUserId);
        Task<RepoResponse<int>> UnwatchAsync(int auctionWatchlistAuctionId, int auctionWatchlistUserId);
    }
}