UPDATE [AUCTIONS] 
	SET [STATUS] = 'CLOSED', [WINNING_BID_ID] = @AUCTION_WINNING_BID_ID, [WINNER_ID] = @AUCTION_WINNER_ID, [CURRENT_PRICE] = @AUCTION_CURRENT_PRICE 
WHERE [IsDeleted] = 0 
	AND [ID] = @PRM_AUCTION_ID