//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.MyecommerceDemo.Common;
using QuickCode.MyecommerceDemo.Common.Extensions;
using QuickCode.MyecommerceDemo.Common.Helpers;
using QuickCode.MyecommerceDemo.IdentityModule.Persistence.Contexts;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Dtos.KafkaEvent;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Mappings;
using QuickCode.MyecommerceDemo.IdentityModule.Persistence.Sql;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.IdentityModule.Persistence.Repositories
{
    public partial class KafkaEventRepository : BaseRepository, IKafkaEventRepository
    {
        public async Task<RepoResponse<List<GetKafkaEventsResponseDto>>> GetKafkaEventsAsync()
        {
            return await ExecuteWithExceptionHandling("GetKafkaEvents", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Query.GetKafkaEvents);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetKafkaEventsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in KafkaEvent");
            });
        }

        public async Task<RepoResponse<List<GetActiveKafkaEventsResponseDto>>> GetActiveKafkaEventsAsync(bool kafkaEventsIsActive)
        {
            return await ExecuteWithExceptionHandling("GetActiveKafkaEvents", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Query.GetActiveKafkaEvents);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetActiveKafkaEventsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in KafkaEvent");
            });
        }

        public async Task<RepoResponse<List<GetTopicWorkflowsResponseDto>>> GetTopicWorkflowsAsync(string kafkaEventsTopicName, HttpMethodType apiMethodDefinitionsHttpMethod)
        {
            return await ExecuteWithExceptionHandling("GetTopicWorkflows", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Query.GetTopicWorkflows);
                var parameters = new
                {
                    PRM_KafkaEvents_TopicName = kafkaEventsTopicName,
                    PRM_ApiMethodDefinitions_HttpMethod = apiMethodDefinitionsHttpMethod
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var values = await connection.QueryAsync<GetTopicWorkflowsResponseDto>(sql, parameters);
                return BuildListResponse(values, "Not found in KafkaEvent");
            });
        }

        public async Task<RepoResponse<List<GetTopicWorkflowsKafkaEventsResponseDto>>> GetTopicWorkflowsKafkaEventsAsync(string kafkaEventsTopicName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetTopicWorkflowsKafkaEvents", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetTopicWorkflowsKafkaEventsResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.KafkaEvent.Query.GetTopicWorkflowsKafkaEvents);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_KafkaEvents_TopicName = kafkaEventsTopicName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetTopicWorkflowsKafkaEventsResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in KafkaEvent");
                }
            });
        }
    }
}