//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.PaymentProcessingModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.PaymentProcessingModule.Application.Dtos.Payment
{
    public record GetPaymentWithGatewayResponseDto
    {
        public int Id { get; init; }
        public Guid ReferenceId { get; init; }
        public int OrderId { get; init; }
        public int CustomerId { get; init; }
        public decimal Amount { get; init; }
        public string CurrencyCode { get; init; }
        public PaymentStatus Status { get; init; }
        public int PaymentGatewayId { get; init; }
        public string GatewayTransactionId { get; init; }
        public DateTime CreatedDate { get; init; }
        public DateTime UpdatedDate { get; init; }
        public string GatewayName { get; init; }
    }
}