SELECT SM.[ID], SM.[NAME], SM.[COST] 
FROM [SHIPPING_METHODS] SM 
WHERE SM.[IsDeleted] = 0 
	AND SM.[IS_ACTIVE] = @PRM_SHIPPING_METHOD_IS_ACTIVE 
ORDER BY SM.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 