//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.MyecommerceDemo.Common;
using QuickCode.MyecommerceDemo.Common.Extensions;
using QuickCode.MyecommerceDemo.Common.Helpers;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Persistence.Contexts;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Dtos.AuctionItem;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Mappings;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Persistence.Sql;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.AuctionManagementModule.Persistence.Repositories
{
    public partial class AuctionItemRepository : BaseRepository, IAuctionItemRepository
    {
        public async Task<RepoResponse<int>> MarkAsUnavailableAsync(int auctionItemId, MarkAsUnavailableRequestDto updateRequest)
        {
            return await ExecuteWithExceptionHandling("AuctionItem", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.AuctionItem.Command.MarkAsUnavailable);
                var parameters = new
                {
                    PRM_AUCTION_ITEM_ID = auctionItemId
                };
                using var connection = await GetOpenConnectionAsync(_writeContext);
                var result = await connection.ExecuteAsync(sql, parameters);
                return new RepoResponse<int>(result, "Success");
            });
        }
    }
}