SELECT A.[ID], A.[FULL_ADDRESS], A.[IS_DEFAULT_SHIPPING], A.[IS_DEFAULT_BILLING] 
FROM [ADDRESSES] A 
WHERE A.[IsDeleted] = 0 
	AND A.[CUSTOMER_ID] = @PRM_ADDRESS_CUSTOMER_ID 
ORDER BY A.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 