SELECT TOP 1 A.[ID], A.[FULL_ADDRESS] 
FROM [ADDRESSES] A 
WHERE A.[IsDeleted] = 0 
	AND A.[CUSTOMER_ID] = @PRM_ADDRESS_CUSTOMER_ID 
	AND A.[IS_DEFAULT_BILLING] = @PRM_ADDRESS_IS_DEFAULT_BILLING 
ORDER BY A.[ID] 