SELECT TL.[ID], TL.[LOG_LEVEL], TL.[MESSAGE], TL.[TIMESTAMP] 
FROM [TRANSACTION_LOGS] TL 
WHERE TL.[IsDeleted] = 0 
	AND TL.[PAYMENT_ID] = @PRM_TRANSACTION_LOG_PAYMENT_ID 
ORDER BY TL.[TIMESTAMP] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 