SELECT TL.[ID], TL.[PAYMENT_ID], TL.[LOG_LEVEL], TL.[MESSAGE] 
FROM [TRANSACTION_LOGS] TL 
WHERE TL.[IsDeleted] = 0 
	AND TL.[MESSAGE] LIKE '%' + @PRM_TRANSACTION_LOG_MESSAGE + '%' 
ORDER BY TL.[TIMESTAMP] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 