SELECT TOP 1 AVG(PR.[RATING]) AS AVERAGE_RATING,
	COUNT(*) AS REVIEW_COUNT 
FROM [PRODUCT_REVIEWS] PR 
WHERE PR.[IsDeleted] = 0 
	AND PR.[PRODUCT_ID] = @PRM_PRODUCT_REVIEW_PRODUCT_ID 
	AND PR.[IS_APPROVED] = @PRM_PRODUCT_REVIEW_IS_APPROVED 