SELECT PR.[ID], PR.[RATING], PR.[TITLE], PR.[COMMENT], PR.[CREATED_DATE] 
FROM [PRODUCT_REVIEWS] PR 
WHERE PR.[IsDeleted] = 0 
	AND PR.[PRODUCT_ID] = @PRM_PRODUCT_REVIEW_PRODUCT_ID 
	AND PR.[IS_APPROVED] = @PRM_PRODUCT_REVIEW_IS_APPROVED 
ORDER BY PR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 