SELECT PR.[ID], PR.[PRODUCT_ID], PR.[RATING], PR.[TITLE], PR.[COMMENT], PR.[IS_APPROVED] 
FROM [PRODUCT_REVIEWS] PR 
WHERE PR.[IsDeleted] = 0 
	AND PR.[CUSTOMER_ID] = @PRM_PRODUCT_REVIEW_CUSTOMER_ID 
ORDER BY PR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 