SELECT PR.[ID], PR.[PRODUCT_ID], PR.[RATING], PR.[TITLE], PR.[COMMENT] 
FROM [PRODUCT_REVIEWS] PR 
WHERE PR.[IsDeleted] = 0 
	AND PR.[IS_APPROVED] = @PRM_PRODUCT_REVIEW_IS_APPROVED 
ORDER BY PR.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 