SELECT PG.[ID], PG.[NAME], PG.[PROVIDER_CODE] 
FROM [PAYMENT_GATEWAYS] PG 
WHERE PG.[IsDeleted] = 0 
	AND PG.[IS_ACTIVE] = @PRM_PAYMENT_GATEWAY_IS_ACTIVE 
ORDER BY PG.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 