//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Dtos.OrderNote;
using System.Threading.Tasks;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.OrderManagementModule.Application.Interfaces.Repositories
{
    public partial interface IOrderNoteRepository : IBaseRepository<OrderNoteDto>
    {
        Task<RepoResponse<OrderNoteDto>> GetByPkAsync(int id);
        Task<RepoResponse<List<GetByOrderIdResponseDto>>> GetByOrderIdAsync(int orderNoteOrderId, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<List<GetCustomerVisibleNotesResponseDto>>> GetCustomerVisibleNotesAsync(int orderNoteOrderId, bool orderNoteIsCustomerVisible, int? pageNumber = null, int? pageSize = null);
    }
}