SELECT 
			ON.[NOTE], 
			ON.[CREATED_DATE] 
FROM [ORDER_NOTES] 
			ON 
WHERE 
			ON.[IsDeleted] = 0 
	AND 
			ON.[ORDER_ID] = @PRM_ORDER_NOTE_ORDER_ID 
	AND 
			ON.[IS_CUSTOMER_VISIBLE] = @PRM_ORDER_NOTE_IS_CUSTOMER_VISIBLE 
ORDER BY 
			ON.[CREATED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 