//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Dtos.AuctionItem
{
    public record AuctionItemDto
    {
        public int Id { get; init; }
        public int ProductId { get; init; }
        public string Name { get; init; }
        public string Description { get; init; }
        public string Condition { get; init; }
        public int OwnerId { get; init; }
        public bool IsAvailable { get; init; }
    }
}