SELECT BIR.[ID], BIR.[PRICE_FROM], BIR.[PRICE_TO], BIR.[INCREMENT_AMOUNT] 
FROM [BID_INCREMENT_RULES] BIR 
WHERE BIR.[IsDeleted] = 0 
	AND BIR.[IS_ACTIVE] = @PRM_BID_INCREMENT_RULE_IS_ACTIVE 
ORDER BY BIR.[PRICE_FROM] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 