//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.PaymentProcessingModule.Application.Dtos.Payment;
using QuickCode.MyecommerceDemo.PaymentProcessingModule.Domain.Entities;
using QuickCode.MyecommerceDemo.PaymentProcessingModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.PaymentProcessingModule.Application.Mappings
{
    public static class PaymentMappings
    {
        public static List<PaymentDto> ToDto(this IEnumerable<Payment> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PaymentDto ToDto(this Payment model)
        {
            return new PaymentDto
            {
                Id = model.Id,
                ReferenceId = model.ReferenceId,
                OrderId = model.OrderId,
                CustomerId = model.CustomerId,
                Amount = model.Amount,
                CurrencyCode = model.CurrencyCode,
                Status = model.Status,
                PaymentGatewayId = model.PaymentGatewayId,
                GatewayTransactionId = model.GatewayTransactionId,
                CreatedDate = model.CreatedDate,
                UpdatedDate = model.UpdatedDate
            };
        }

        public static Payment ToEntity(this PaymentDto model)
        {
            return new Payment
            {
                Id = model.Id,
                ReferenceId = model.ReferenceId,
                OrderId = model.OrderId,
                CustomerId = model.CustomerId,
                Amount = model.Amount,
                CurrencyCode = model.CurrencyCode,
                Status = model.Status,
                PaymentGatewayId = model.PaymentGatewayId,
                GatewayTransactionId = model.GatewayTransactionId,
                CreatedDate = model.CreatedDate,
                UpdatedDate = model.UpdatedDate
            };
        }
    }
}