SELECT C.[ID], C.[NAME], C.[SLUG] 
FROM [CATEGORIES] C 
WHERE C.[IsDeleted] = 0 
	AND C.[PARENT_CATEGORY_ID] = @PRM_CATEGORY_PARENT_CATEGORY_ID 
ORDER BY C.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 