//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Dtos.AspNetUserToken;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.IdentityModule.Application.Mappings
{
    public static class AspNetUserTokenMappings
    {
        public static List<AspNetUserTokenDto> ToDto(this IEnumerable<AspNetUserToken> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AspNetUserTokenDto ToDto(this AspNetUserToken model)
        {
            return new AspNetUserTokenDto
            {
                UserId = model.UserId,
                LoginProvider = model.LoginProvider,
                Name = model.Name,
                Value = model.Value
            };
        }

        public static AspNetUserToken ToEntity(this AspNetUserTokenDto model)
        {
            return new AspNetUserToken
            {
                UserId = model.UserId,
                LoginProvider = model.LoginProvider,
                Name = model.Name,
                Value = model.Value
            };
        }
    }
}