//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Dtos.ColumnType;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.IdentityModule.Application.Mappings
{
    public static class ColumnTypeMappings
    {
        public static List<ColumnTypeDto> ToDto(this IEnumerable<ColumnType> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ColumnTypeDto ToDto(this ColumnType model)
        {
            return new ColumnTypeDto
            {
                Id = model.Id,
                TypeName = model.TypeName,
                IosComponentName = model.IosComponentName,
                IosType = model.IosType,
                IconCode = model.IconCode
            };
        }

        public static ColumnType ToEntity(this ColumnTypeDto model)
        {
            return new ColumnType
            {
                Id = model.Id,
                TypeName = model.TypeName,
                IosComponentName = model.IosComponentName,
                IosType = model.IosType,
                IconCode = model.IconCode
            };
        }
    }
}