//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Dtos.Module;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.IdentityModule.Application.Mappings
{
    public static class ModuleMappings
    {
        public static List<ModuleDto> ToDto(this IEnumerable<Module> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static ModuleDto ToDto(this Module model)
        {
            return new ModuleDto
            {
                Name = model.Name,
                Description = model.Description
            };
        }

        public static Module ToEntity(this ModuleDto model)
        {
            return new Module
            {
                Name = model.Name,
                Description = model.Description
            };
        }
    }
}