//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Dtos.PortalPageDefinition;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.IdentityModule.Application.Mappings
{
    public static class PortalPageDefinitionMappings
    {
        public static List<PortalPageDefinitionDto> ToDto(this IEnumerable<PortalPageDefinition> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static PortalPageDefinitionDto ToDto(this PortalPageDefinition model)
        {
            return new PortalPageDefinitionDto
            {
                Key = model.Key,
                ModuleName = model.ModuleName,
                ModelName = model.ModelName,
                PageAction = model.PageAction,
                PagePath = model.PagePath
            };
        }

        public static PortalPageDefinition ToEntity(this PortalPageDefinitionDto model)
        {
            return new PortalPageDefinition
            {
                Key = model.Key,
                ModuleName = model.ModuleName,
                ModelName = model.ModelName,
                PageAction = model.PageAction,
                PagePath = model.PagePath
            };
        }
    }
}