SELECT TOP 1 AS.[ID], AS.[WINNER_ID], AS.[FINAL_AMOUNT], AS.[IS_PAID] 
FROM [AUCTION_SETTLEMENTS] AS 
WHERE AS.[IsDeleted] = 0 
	AND AS.[AUCTION_ID] = @PRM_AUCTION_SETTLEMENT_AUCTION_ID 
ORDER BY AS.[ID] 