SELECT AS.[ID], AS.[AUCTION_ID], AS.[WINNER_ID], AS.[FINAL_AMOUNT] 
FROM [AUCTION_SETTLEMENTS] AS 
WHERE AS.[IsDeleted] = 0 
	AND AS.[IS_PAID] = @PRM_AUCTION_SETTLEMENT_IS_PAID 
	AND AS.[PAYMENT_DUE_DATE] < GETDATE() 
ORDER BY AS.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 