// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Persistence.Contexts;

#nullable disable

namespace QuickCode.MyecommerceDemo.AuctionManagementModule.Persistence.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260406231628_AutoMigration_20260406_231451_127")]
    partial class AutoMigration_20260406_231451_127
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("CURRENT_PRICE");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("END_TIME");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("ItemDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ITEM_DESCRIPTION");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("ITEM_ID");

                    b.Property<string>("ItemName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ITEM_NAME");

                    b.Property<decimal>("ReservePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("RESERVE_PRICE");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("SELLER_ID");

                    b.Property<decimal>("StartPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("START_PRICE");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("START_TIME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'DRAFT'");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int")
                        .HasColumnName("WINNER_ID");

                    b.Property<int>("WinningBidId")
                        .HasColumnType("int")
                        .HasColumnName("WINNING_BID_ID");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.HasIndex("ItemId");

                    b.HasIndex("WinningBidId");

                    b.ToTable("AUCTIONS");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.AuctionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CONDITION");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_AVAILABLE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NAME");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("OWNER_ID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("AUCTION_ITEMS");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.AuctionSettlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("AUCTION_ID");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("FINAL_AMOUNT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_PAID");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PAID_DATE");

                    b.Property<DateTime>("PaymentDueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PAYMENT_DUE_DATE");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("PAYMENT_ID");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int")
                        .HasColumnName("WINNER_ID");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("AUCTION_SETTLEMENTS");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.AuctionWatchlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("AUCTION_ID");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("AUCTION_WATCHLISTS");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ACTION");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGE_SUMMARY");

                    b.Property<string>("ChangedColumns")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CHANGED_COLUMNS");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CORRELATION_ID");

                    b.Property<string>("EntityId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_ID");

                    b.Property<string>("EntityName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ENTITY_NAME");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ERROR_MESSAGE");

                    b.Property<string>("Hash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("HASH");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<bool>("IsChanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_CHANGED");

                    b.Property<bool>("IsSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_SUCCESS");

                    b.Property<string>("NewValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NEW_VALUES");

                    b.Property<string>("OldValues")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OLD_VALUES");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("USER_AGENT");

                    b.Property<string>("UserGroup")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_GROUP");

                    b.Property<string>("UserId")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("UserName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("AUDIT_LOGS");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int")
                        .HasColumnName("AUCTION_ID");

                    b.Property<decimal>("BidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BID_AMOUNT");

                    b.Property<DateTime>("BidTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("BID_TIME");

                    b.Property<int>("BidderId")
                        .HasColumnType("int")
                        .HasColumnName("BIDDER_ID");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("STATUS")
                        .HasDefaultValueSql("'ACTIVE'");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("BIDS");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.BidIncrementRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedOnUtc");

                    b.Property<decimal>("IncrementAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("INCREMENT_AMOUNT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IS_ACTIVE");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<decimal>("PriceFrom")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRICE_FROM");

                    b.Property<decimal>("PriceTo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRICE_TO");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasFilter("IsDeleted = 0");

                    b.ToTable("BID_INCREMENT_RULES");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Auction", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.AuctionItem", "AuctionItem")
                        .WithMany("Auctions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Bid", "Bid")
                        .WithMany("Auctions")
                        .HasForeignKey("WinningBidId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuctionItem");

                    b.Navigation("Bid");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.AuctionSettlement", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Auction", "Auction")
                        .WithMany("AuctionSettlements")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.AuctionWatchlist", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Auction", "Auction")
                        .WithMany("AuctionWatchlists")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Bid", b =>
                {
                    b.HasOne("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Auction", b =>
                {
                    b.Navigation("AuctionSettlements");

                    b.Navigation("AuctionWatchlists");

                    b.Navigation("Bids");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.AuctionItem", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities.Bid", b =>
                {
                    b.Navigation("Auctions");
                });
#pragma warning restore 612, 618
        }
    }
}
