SELECT A.[ID], A.[ITEM_NAME], A.[STATUS], A.[CURRENT_PRICE] 
FROM [AUCTIONS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[SELLER_ID] = @PRM_AUCTION_SELLER_ID 
ORDER BY A.[CREATED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 