SELECT A.[ID], A.[RESERVE_PRICE] 
FROM [AUCTIONS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[STATUS] = @PRM_AUCTION_STATUS 
	AND A.[END_TIME] < GETDATE() 
ORDER BY A.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 