SELECT A.[ID], A.[ITEM_NAME], A.[CURRENT_PRICE], A.[END_TIME] 
FROM [AUCTIONS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[STATUS] = @PRM_AUCTION_STATUS 
	AND A.[END_TIME] < DATEADD(HOUR,
	24,
	GETDATE()) 
ORDER BY A.[END_TIME] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 