SELECT A.[ID], A.[WINNER_ID], A.[WINNING_BID_ID] 
FROM [AUCTIONS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[STATUS] = @PRM_AUCTION_STATUS 
ORDER BY A.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 