SELECT A.[ID], A.[ITEM_NAME], A.[START_PRICE], A.[START_TIME] 
FROM [AUCTIONS] A 
WHERE A.[IsDeleted] = 0 
	AND A.[STATUS] = @PRM_AUCTION_STATUS 
ORDER BY A.[START_TIME] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 