//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Domain.Entities;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.MyecommerceDemo.Common;
using QuickCode.MyecommerceDemo.Common.Extensions;
using QuickCode.MyecommerceDemo.Common.Helpers;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Persistence.Contexts;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Dtos.Brand;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Mappings;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Persistence.Sql;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.ProductCatalogModule.Persistence.Repositories
{
    public partial class BrandRepository : BaseRepository, IBrandRepository
    {
        public async Task<RepoResponse<List<GetActiveResponseDto>>> GetActiveAsync(bool brandIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetActive", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Brand.Query.GetActive);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_BRAND_IS_ACTIVE = brandIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetActiveResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Brand");
                }
            });
        }

        public async Task<RepoResponse<List<SearchByNameResponseDto>>> SearchByNameAsync(string brandName, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("SearchByName", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<SearchByNameResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Brand.Query.SearchByName);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_BRAND_NAME = brandName,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<SearchByNameResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Brand");
                }
            });
        }
    }
}