SELECT R.[ID], R.[AMOUNT], R.[STATUS], R.[REQUESTED_DATE] 
FROM [REFUNDS] R 
WHERE R.[IsDeleted] = 0 
	AND R.[PAYMENT_ID] = @PRM_REFUND_PAYMENT_ID 
ORDER BY R.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 