SELECT R.[ID], R.[PAYMENT_ID], R.[AMOUNT], R.[REASON] 
FROM [REFUNDS] R 
WHERE R.[IsDeleted] = 0 
	AND R.[STATUS] = @PRM_REFUND_STATUS 
ORDER BY R.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 