//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.MyecommerceDemo.Common;
using QuickCode.MyecommerceDemo.Common.Extensions;
using QuickCode.MyecommerceDemo.IdentityModule.Persistence.Contexts;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Dtos.RefreshToken;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Mappings;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.IdentityModule.Persistence.Repositories
{
    public partial class RefreshTokenRepository : BaseRepository, IRefreshTokenRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        public RefreshTokenRepository(ILogger<RefreshTokenRepository> logger, WriteDbContext writeContext, ReadDbContext readContext) : base(logger, "RefreshToken")
        {
            _writeContext = writeContext;
            _readContext = readContext;
        }

        public async Task<RepoResponse<RefreshTokenDto>> InsertAsync(RefreshTokenDto value)
        {
            return await ExecuteWithExceptionHandling("Insert", async () =>
            {
                var entity = value.ToEntity();
                await _writeContext.RefreshToken.AddAsync(entity);
                await _writeContext.SaveChangesAsync();
                var resultDto = entity.ToDto();
                return new RepoResponse<RefreshTokenDto>(resultDto, "Success");
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(RefreshTokenDto value)
        {
            return await ExecuteWithExceptionHandling("Update", async () =>
            {
                _writeContext.Set<Domain.Entities.RefreshToken>().Update(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(RefreshTokenDto value)
        {
            return await ExecuteWithExceptionHandling("Delete", async () =>
            {
                _writeContext.RefreshToken.Remove(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<RefreshTokenDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling("GetByPk", async () =>
            {
                var result =
                    from RT in _readContext.RefreshToken
                    where RT.Id.Equals(id)
                    select RT;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<RefreshTokenDto>
                {
                    Code = 404,
                    Message = "Not found in RefreshToken"
                }

                : new RepoResponse<RefreshTokenDto>(response.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<List<RefreshTokenDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling("Select", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<RefreshTokenDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var query = _readContext.RefreshToken.OrderBy(o => o.Id).AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = ApplyPagination(query, pageNumber.Value, pageSize.Value);
                }

                var result = await query.ToListAsync();
                return new RepoResponse<List<RefreshTokenDto>>(result.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling("Count", async () =>
            {
                return new RepoResponse<int>(await _readContext.RefreshToken.CountAsync(), "Success");
            });
        }
    }
}