SELECT O.[ID], O.[ORDER_NUMBER], O.[STATUS], O.[TOTAL_AMOUNT], O.[CREATED_DATE] 
FROM [ORDERS] O 
WHERE O.[IsDeleted] = 0 
	AND O.[CUSTOMER_ID] = @PRM_ORDER_CUSTOMER_ID 
ORDER BY O.[CREATED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 