SELECT O.[ID], O.[ORDER_NUMBER], O.[CUSTOMER_ID], O.[TOTAL_AMOUNT] 
FROM [ORDERS] O 
WHERE O.[IsDeleted] = 0 
	AND O.[STATUS] = @PRM_ORDER_STATUS 
ORDER BY O.[CREATED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 