SELECT O.[ID], O.[ORDER_NUMBER], O.[SHIPPING_ADDRESS_ID] 
FROM [ORDERS] O 
WHERE O.[IsDeleted] = 0 
	AND O.[STATUS] = @PRM_ORDER_STATUS 
ORDER BY O.[CREATED_DATE] ASC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 