SELECT TOP 1 O.[ID], O.[ORDER_NUMBER], O.[CUSTOMER_ID], O.[STATUS], O.[TOTAL_AMOUNT], O.[SHIPPING_ADDRESS_ID], O.[BILLING_ADDRESS_ID], O.[SHIPPING_METHOD_ID], O.[PAYMENT_ID], O.[CREATED_DATE], O.[UPDATED_DATE], SA.[FULL_ADDRESS] AS SHIPPING_ADDRESS,
	BA.[FULL_ADDRESS] AS BILLING_ADDRESS 
FROM [ORDERS] O 
	INNER JOIN [ADDRESSES] SA 
			ON O.[SHIPPING_ADDRESS_ID] = SA.[ID] 
	INNER JOIN [ADDRESSES] BA 
			ON O.[SHIPPING_ADDRESS_ID] = BA.[ID] 
WHERE O.[IsDeleted] = 0 
	AND SA.[IsDeleted] = 0 
	AND BA.[IsDeleted] = 0 
	AND O.[ID] = @PRM_ORDERS_ID 
	AND O.[SHIPPING_ADDRESS_ID] = @PRM_ORDERS_SHIPPING_ADDRESS_ID 
	AND SA.[ID] = @PRM_ADDRESSES_ID 
	AND O.[BILLING_ADDRESS_ID] = @PRM_ORDERS_BILLING_ADDRESS_ID 
	AND BA.[ID] = @PRM_ADDRESSES_ID 
ORDER BY O.[ID] 