SELECT O.[ID], O.[ORDER_NUMBER], O.[STATUS], O.[TOTAL_AMOUNT] 
FROM [ORDERS] O 
WHERE O.[IsDeleted] = 0 
	AND O.[CREATED_DATE] > DATEADD(DAY, -7,
	GETDATE()) 
ORDER BY O.[CREATED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 