//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using QuickCode.MyecommerceDemo.Portal.Models;
using QuickCode.MyecommerceDemo.Portal.Models.IdentityModule;
using QuickCode.MyecommerceDemo.Portal.Helpers;
using Microsoft.AspNetCore.Mvc;
using IdentityModuleContracts = QuickCode.MyecommerceDemo.Common.Nswag.Clients.IdentityModuleApi.Contracts;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using QuickCode.MyecommerceDemo.Portal.Helpers.Authorization;
using Microsoft.AspNetCore.Http;
using System.Threading;
using System.Threading.Tasks;
using AutoRest.Core.Utilities.Collections;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace QuickCode.MyecommerceDemo.Portal.Controllers.IdentityModule
{
    [Permission("IdentityModulePortalPageAccessGrants")]
    [Area("IdentityModule")]
    [Route("IdentityModulePortalPageAccessGrants")]
    public partial class PortalPageAccessGrantsController : BaseController
    {
        private readonly IdentityModuleContracts.IPortalPageAccessGrantsClient pageClient;
        private readonly IdentityModuleContracts.IPermissionGroupsClient pagePermissionGroupClient;
        private readonly IdentityModuleContracts.IPortalPageDefinitionsClient pagePortalPageDefinitionClient;
        public PortalPageAccessGrantsController(IdentityModuleContracts.IPortalPageAccessGrantsClient pageClient, IdentityModuleContracts.IPermissionGroupsClient pagePermissionGroupClient, IdentityModuleContracts.IPortalPageDefinitionsClient pagePortalPageDefinitionClient, IdentityModuleContracts.ITableComboboxSettingsClient tableComboboxSettingsClient, IHttpContextAccessor httpContextAccessor, IMemoryCache cache) : base(tableComboboxSettingsClient, httpContextAccessor, cache)
        {
            this.pageClient = pageClient;
            this.pagePermissionGroupClient = pagePermissionGroupClient;
            this.pagePortalPageDefinitionClient = pagePortalPageDefinitionClient;
        }

        [ResponseCache(VaryByQueryKeys = new[] { "ic" }, Duration = 30)]
        public async Task<IActionResult> GetImage(string ic)
        {
            return await GetImageResult(pageClient, ic);
        }

        [Route("List")]
        public async Task<IActionResult> List()
        {
            var model = await PrepareModel();
            model.ComboList = await FillPageComboBoxes(model.ComboList);
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("List")]
        [HttpPost]
        public async Task<IActionResult> List(PortalPageAccessGrantData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = new();
            SetModelBinder(ref model);
            return View("List", model);
        }

        [Route("Insert")]
        [HttpPost]
        public async Task<IActionResult> Insert(PortalPageAccessGrantData model)
        {
            ModelBinder(ref model);
            var result = await pageClient.PortalPageAccessGrantsInsertAsync(model.SelectedItem);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Update")]
        [HttpPost]
        public async Task<IActionResult> Update(PortalPageAccessGrantData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.PortalPageAccessGrantsUpdateAsync(request.PermissionGroupName, request.PortalPageDefinitionKey, request.PageAction, request);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("Delete")]
        [HttpPost]
        public async Task<IActionResult> Delete(PortalPageAccessGrantData model)
        {
            ModelBinder(ref model);
            var request = model.SelectedItem;
            var result = await pageClient.PortalPageAccessGrantsDeleteAsync(request.PermissionGroupName, request.PortalPageDefinitionKey, request.PageAction);
            ClearCache();
            SetModelBinder(ref model);
            return Ok(result);
        }

        [Route("InsertItem")]
        public IActionResult InsertItem(PortalPageAccessGrantData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            SetModelBinder(ref model);
            model.SelectedItem = new();
            return PartialView("Insert", model);
        }

        [Route("DetailItem")]
        public async Task<IActionResult> DetailItem(PortalPageAccessGrantData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Detail", model);
        }

        [Route("UpdateItem")]
        [HttpPost]
        public async Task<IActionResult> UpdateItem(PortalPageAccessGrantData model)
        {
            ModelState.Clear();
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Update", model);
        }

        [Route("DeleteItem")]
        [HttpPost]
        public async Task<IActionResult> DeleteItem(PortalPageAccessGrantData model)
        {
            ModelBinder(ref model);
            model = await PrepareModel(model);
            model.SelectedItem = model.List.Find(i => i.GetKey() == model.SelectedKey);
            SetModelBinder(ref model);
            return PartialView("Delete", model);
        }

        private async Task<PortalPageAccessGrantData> PrepareModel()
        {
            var model = GetModel<PortalPageAccessGrantData>();
            model.CurrentPage = 1;
            model.PageSize = PageSize;
            return await PrepareModel(model);
        }

        private async Task<PortalPageAccessGrantData> PrepareModel(PortalPageAccessGrantData model)
        {
            model.NumberOfRecord = await pageClient.PortalPageAccessGrantsCountAsync();
            model.TotalPage = (model.NumberOfRecord + PageSize - 1) / PageSize;
            model.List = (await pageClient.PortalPageAccessGrantsListAsync(model.CurrentPage, PageSize)).ToList();
            return model;
        }

        private async Task<Dictionary<string, Dictionary<string, string>>> FillPageComboBoxes(Dictionary<string, Dictionary<string, string>> comboBoxList)
        {
            comboBoxList.Clear();
            comboBoxList.AddRange(await FillComboBoxAsync("PermissionGroups", () => pagePermissionGroupClient.PermissionGroupsListAsync()));
            comboBoxList.AddRange(await FillComboBoxAsync("PortalPageDefinitions", () => pagePortalPageDefinitionClient.PortalPageDefinitionsListAsync()));
            return comboBoxList;
        }
    }
}