//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.MyecommerceDemo.Common;
using QuickCode.MyecommerceDemo.Common.Extensions;
using QuickCode.MyecommerceDemo.Common.Helpers;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Persistence.Contexts;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Dtos.BidIncrementRule;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Application.Mappings;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Persistence.Sql;
using QuickCode.MyecommerceDemo.AuctionManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.AuctionManagementModule.Persistence.Repositories
{
    public partial class BidIncrementRuleRepository : BaseRepository, IBidIncrementRuleRepository
    {
        public async Task<RepoResponse<List<GetActiveRulesResponseDto>>> GetActiveRulesAsync(bool bidIncrementRuleIsActive, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetActiveRules", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetActiveRulesResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.BidIncrementRule.Query.GetActiveRules);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_BID_INCREMENT_RULE_IS_ACTIVE = bidIncrementRuleIsActive,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetActiveRulesResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in BidIncrementRule");
                }
            });
        }

        public async Task<RepoResponse<GetIncrementForPriceResponseDto>> GetIncrementForPriceAsync(bool bidIncrementRuleIsActive)
        {
            return await ExecuteWithExceptionHandling("GetIncrementForPrice", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.BidIncrementRule.Query.GetIncrementForPrice);
                var parameters = new
                {
                    PRM_BID_INCREMENT_RULE_IS_ACTIVE = bidIncrementRuleIsActive
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetIncrementForPriceResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in BidIncrementRule");
            });
        }
    }
}