SELECT GC.[ID], GC.[CONFIG_KEY], GC.[CONFIG_VALUE] 
FROM [GATEWAY_CONFIGS] GC 
WHERE GC.[IsDeleted] = 0 
	AND GC.[GATEWAY_ID] = @PRM_GATEWAY_CONFIG_GATEWAY_ID 
	AND GC.[IS_SECRET] = @PRM_GATEWAY_CONFIG_IS_SECRET 
ORDER BY GC.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 