SELECT P.[ID], P.[AMOUNT], P.[STATUS], P.[CREATED_DATE] 
FROM [PAYMENTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[ORDER_ID] = @PRM_PAYMENT_ORDER_ID 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 