SELECT TOP 1 SUM(P.[AMOUNT]) AS TOTAL_VOLUME,
	COUNT(*) AS TRANSACTION_COUNT 
FROM [PAYMENTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[CREATED_DATE] > DATEADD(DAY, -1,
	GETDATE()) 
	AND P.[STATUS] = @PRM_PAYMENT_STATUS 