SELECT P.[ID], P.[ORDER_ID], P.[AMOUNT] 
FROM [PAYMENTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[STATUS] = @PRM_PAYMENT_STATUS 
ORDER BY P.[CREATED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 