SELECT TOP 1 P.[ID], P.[REFERENCE_ID], P.[ORDER_ID], P.[CUSTOMER_ID], P.[AMOUNT], P.[CURRENCY_CODE], P.[STATUS], P.[PAYMENT_GATEWAY_ID], P.[GATEWAY_TRANSACTION_ID], P.[CREATED_DATE], P.[UPDATED_DATE], G.[NAME] AS GATEWAY_NAME 
FROM [PAYMENTS] P 
	INNER JOIN [PAYMENT_GATEWAYS] G 
			ON P.[PAYMENT_GATEWAY_ID] = G.[ID] 
WHERE P.[IsDeleted] = 0 
	AND G.[IsDeleted] = 0 
	AND P.[ID] = @PRM_PAYMENTS_ID 
	AND P.[PAYMENT_GATEWAY_ID] = @PRM_PAYMENTS_PAYMENT_GATEWAY_ID 
	AND G.[ID] = @PRM_PAYMENT_GATEWAYS_ID 
ORDER BY P.[ID] 