SELECT AI.[ID], AI.[NAME], AI.[CONDITION] 
FROM [AUCTION_ITEMS] AI 
WHERE AI.[IsDeleted] = 0 
	AND AI.[OWNER_ID] = @PRM_AUCTION_ITEM_OWNER_ID 
	AND AI.[IS_AVAILABLE] = @PRM_AUCTION_ITEM_IS_AVAILABLE 
ORDER BY AI.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 