//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Dtos.KafkaEvent;
using System.Threading.Tasks;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface IKafkaEventRepository : IBaseRepository<KafkaEventDto>
    {
        Task<RepoResponse<KafkaEventDto>> GetByPkAsync(string topicName);
        Task<RepoResponse<List<GetKafkaEventsResponseDto>>> GetKafkaEventsAsync();
        Task<RepoResponse<List<GetActiveKafkaEventsResponseDto>>> GetActiveKafkaEventsAsync(bool kafkaEventsIsActive);
        Task<RepoResponse<List<GetTopicWorkflowsResponseDto>>> GetTopicWorkflowsAsync(string kafkaEventsTopicName, HttpMethodType apiMethodDefinitionsHttpMethod);
        Task<RepoResponse<List<GetTopicWorkflowsKafkaEventsResponseDto>>> GetTopicWorkflowsKafkaEventsAsync(string kafkaEventsTopicName, int? pageNumber = null, int? pageSize = null);
        Task<RepoResponse<int>> CleanKafkaEventsWithModuleNameAsync(string apiMethodDefinitionsModuleName);
        Task<RepoResponse<int>> CleanKafkaEventsWithModelNameAsync(string apiMethodDefinitionsModelName);
    }
}