//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Entities;
using QuickCode.MyecommerceDemo.IdentityModule.Application.Dtos.PortalPageAccessGrant;
using System.Threading.Tasks;
using QuickCode.MyecommerceDemo.IdentityModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.IdentityModule.Application.Interfaces.Repositories
{
    public partial interface IPortalPageAccessGrantRepository : IBaseRepository<PortalPageAccessGrantDto>
    {
        Task<RepoResponse<PortalPageAccessGrantDto>> GetByPkAsync(string permissionGroupName, string portalPageDefinitionKey, PageActionType pageAction);
        Task<RepoResponse<List<GetPortalPageAccessGrantsResponseDto>>> GetPortalPageAccessGrantsAsync(string portalPageAccessGrantPermissionGroupName);
        Task<RepoResponse<List<GetPortalPageAccessGrantResponseDto>>> GetPortalPageAccessGrantAsync(string portalPageAccessGrantPermissionGroupName, string portalPageAccessGrantPortalPageDefinitionKey, PageActionType portalPageAccessGrantPageAction);
        Task<RepoResponse<int>> ClearPortalPageAccessGrantsAsync();
    }
}