SELECT OSH.[ID], OSH.[NEW_STATUS], OSH.[REASON], OSH.[CHANGED_DATE] 
FROM [ORDER_STATUS_HISTORIES] OSH 
WHERE OSH.[IsDeleted] = 0 
	AND OSH.[ORDER_ID] = @PRM_ORDER_STATUS_HISTORY_ORDER_ID 
ORDER BY OSH.[CHANGED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 