SELECT PM.[ID], PM.[METHOD_TYPE], PM.[CARD_BRAND], PM.[LAST_FOUR_DIGITS], PM.[IS_DEFAULT] 
FROM [PAYMENT_METHODS] PM 
WHERE PM.[IsDeleted] = 0 
	AND PM.[CUSTOMER_ID] = @PRM_PAYMENT_METHOD_CUSTOMER_ID 
	AND PM.[IS_ACTIVE] = @PRM_PAYMENT_METHOD_IS_ACTIVE 
ORDER BY PM.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 