SELECT TOP 1 PM.[ID], PM.[TOKEN] 
FROM [PAYMENT_METHODS] PM 
WHERE PM.[IsDeleted] = 0 
	AND PM.[CUSTOMER_ID] = @PRM_PAYMENT_METHOD_CUSTOMER_ID 
	AND PM.[IS_DEFAULT] = @PRM_PAYMENT_METHOD_IS_DEFAULT 
	AND PM.[IS_ACTIVE] = @PRM_PAYMENT_METHOD_IS_ACTIVE 
ORDER BY PM.[ID] 