//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.MyecommerceDemo.Common;
using QuickCode.MyecommerceDemo.Common.Extensions;
using QuickCode.MyecommerceDemo.OrderManagementModule.Persistence.Contexts;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Dtos.Order;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Mappings;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.OrderManagementModule.Persistence.Repositories
{
    public partial class OrderRepository : BaseRepository, IOrderRepository
    {
        private readonly WriteDbContext _writeContext;
        private readonly ReadDbContext _readContext;
        public OrderRepository(ILogger<OrderRepository> logger, WriteDbContext writeContext, ReadDbContext readContext) : base(logger, "Order")
        {
            _writeContext = writeContext;
            _readContext = readContext;
        }

        public async Task<RepoResponse<OrderDto>> InsertAsync(OrderDto value)
        {
            return await ExecuteWithExceptionHandling("Insert", async () =>
            {
                var entity = value.ToEntity();
                await _writeContext.Order.AddAsync(entity);
                await _writeContext.SaveChangesAsync();
                var resultDto = entity.ToDto();
                return new RepoResponse<OrderDto>(resultDto, "Success");
            });
        }

        public async Task<RepoResponse<bool>> UpdateAsync(OrderDto value)
        {
            return await ExecuteWithExceptionHandling("Update", async () =>
            {
                _writeContext.Set<Domain.Entities.Order>().Update(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<bool>> DeleteAsync(OrderDto value)
        {
            return await ExecuteWithExceptionHandling("Delete", async () =>
            {
                _writeContext.Order.Remove(value.ToEntity());
                await _writeContext.SaveChangesAsync();
                return new RepoResponse<bool>(true, "Success");
            });
        }

        public async Task<RepoResponse<OrderDto>> GetByPkAsync(int id)
        {
            return await ExecuteWithExceptionHandling("GetByPk", async () =>
            {
                var result =
                    from O in _readContext.Order
                    where O.Id.Equals(id)
                    select O;
                var response = await result.FirstOrDefaultAsync();
                return response == null ? new RepoResponse<OrderDto>
                {
                    Code = 404,
                    Message = "Not found in Order"
                }

                : new RepoResponse<OrderDto>(response.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<List<OrderDto>>> ListAsync(int? pageNumber = null, int? pageSize = null)
        {
            return await ExecuteWithExceptionHandling("Select", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<OrderDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }

                var query = _readContext.Order.OrderBy(o => o.Id).AsQueryable();
                if (pageNumber.HasValue && pageSize.HasValue)
                {
                    query = ApplyPagination(query, pageNumber.Value, pageSize.Value);
                }

                var result = await query.ToListAsync();
                return new RepoResponse<List<OrderDto>>(result.ToDto(), "Success");
            });
        }

        public async Task<RepoResponse<int>> CountAsync()
        {
            return await ExecuteWithExceptionHandling("Count", async () =>
            {
                return new RepoResponse<int>(await _readContext.Order.CountAsync(), "Success");
            });
        }
    }
}