//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by QuickCode. 
// Runtime Version:1.0
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.SqlClient;
using QuickCode.MyecommerceDemo.Common.Models;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Entities;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Interfaces.Repositories;
using System.Threading.Tasks;
using Dapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QuickCode.MyecommerceDemo.Common;
using QuickCode.MyecommerceDemo.Common.Extensions;
using QuickCode.MyecommerceDemo.Common.Helpers;
using QuickCode.MyecommerceDemo.OrderManagementModule.Persistence.Contexts;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Dtos.Order;
using QuickCode.MyecommerceDemo.OrderManagementModule.Application.Mappings;
using QuickCode.MyecommerceDemo.OrderManagementModule.Persistence.Sql;
using QuickCode.MyecommerceDemo.OrderManagementModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.OrderManagementModule.Persistence.Repositories
{
    public partial class OrderRepository : BaseRepository, IOrderRepository
    {
        public async Task<RepoResponse<List<GetByCustomerIdResponseDto>>> GetByCustomerIdAsync(int orderCustomerId, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByCustomerId", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByCustomerIdResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Order.Query.GetByCustomerId);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ORDER_CUSTOMER_ID = orderCustomerId,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByCustomerIdResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Order");
                }
            });
        }

        public async Task<RepoResponse<GetByOrderNumberResponseDto>> GetByOrderNumberAsync(string orderOrderNumber)
        {
            return await ExecuteWithExceptionHandling("GetByOrderNumber", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Order.Query.GetByOrderNumber);
                var parameters = new
                {
                    PRM_ORDER_ORDER_NUMBER = orderOrderNumber
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetByOrderNumberResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Order");
            });
        }

        public async Task<RepoResponse<List<GetByStatusResponseDto>>> GetByStatusAsync(OrderStatus orderStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetByStatus", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetByStatusResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Order.Query.GetByStatus);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ORDER_STATUS = orderStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetByStatusResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Order");
                }
            });
        }

        public async Task<RepoResponse<List<GetRecentOrdersResponseDto>>> GetRecentOrdersAsync(DateTime orderCreatedDate, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetRecentOrders", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetRecentOrdersResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Order.Query.GetRecentOrders);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetRecentOrdersResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Order");
                }
            });
        }

        public async Task<RepoResponse<List<GetOrdersForFulfillmentResponseDto>>> GetOrdersForFulfillmentAsync(OrderStatus orderStatus, int? pageNumber = null, int? pageSize = null)
        {
            pageNumber ??= ConfigurationConstants.MinPageNumber;
            pageSize ??= ConfigurationConstants.DefaultPageSize;
            return await ExecuteWithExceptionHandling("GetOrdersForFulfillment", async () =>
            {
                if (pageNumber.HasValue && pageNumber < ConfigurationConstants.MinPageNumber)
                {
                    return new RepoResponse<List<GetOrdersForFulfillmentResponseDto>>
                    {
                        Code = 404,
                        Message = $"Page Number must be greater than {ConfigurationConstants.MinPageNumber}"};
                }
                else
                {
                    var sql = SqlLoader.Load(SqlScripts.Order.Query.GetOrdersForFulfillment);
                    var startIndex = (pageNumber - 1) * pageSize;
                    var parameters = new
                    {
                        PRM_ORDER_STATUS = orderStatus,
                        StartIndex = startIndex,
                        PageSize = pageSize
                    };
                    using var connection = await GetOpenConnectionAsync(_readContext);
                    var values = await connection.QueryAsync<GetOrdersForFulfillmentResponseDto>(sql, parameters);
                    return BuildListResponse(values, "Not found in Order");
                }
            });
        }

        public async Task<RepoResponse<GetOrderWithDetailsResponseDto>> GetOrderWithDetailsAsync(int ordersId, int orderShippingAddressId, int orderBillingAddressId, int addressId)
        {
            return await ExecuteWithExceptionHandling("GetOrderWithDetails", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Order.Query.GetOrderWithDetails);
                var parameters = new
                {
                    PRM_ORDERS_ID = ordersId,
                    PRM_ORDERS_SHIPPING_ADDRESS_ID = orderShippingAddressId,
                    PRM_ADDRESSES_ID = addressId,
                    PRM_ORDERS_BILLING_ADDRESS_ID = orderBillingAddressId
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetOrderWithDetailsResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Order");
            });
        }

        public async Task<RepoResponse<GetMonthlyRevenueResponseDto>> GetMonthlyRevenueAsync(DateTime orderCreatedDate)
        {
            return await ExecuteWithExceptionHandling("GetMonthlyRevenue", async () =>
            {
                var sql = SqlLoader.Load(SqlScripts.Order.Query.GetMonthlyRevenue);
                var parameters = new
                {
                };
                using var connection = await GetOpenConnectionAsync(_readContext);
                var value = await connection.QueryFirstOrDefaultAsync<GetMonthlyRevenueResponseDto>(sql, parameters);
                return BuildResponse(value, "Not found in Order");
            });
        }
    }
}