//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Dtos.AuditLog;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Domain.Entities;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Mappings
{
    public static class AuditLogMappings
    {
        public static List<AuditLogDto> ToDto(this IEnumerable<AuditLog> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static AuditLogDto ToDto(this AuditLog model)
        {
            return new AuditLogDto
            {
                Id = model.Id,
                EntityName = model.EntityName,
                EntityId = model.EntityId,
                Action = model.Action,
                UserId = model.UserId,
                UserName = model.UserName,
                UserGroup = model.UserGroup,
                Timestamp = model.Timestamp,
                OldValues = model.OldValues,
                NewValues = model.NewValues,
                ChangedColumns = model.ChangedColumns,
                IsChanged = model.IsChanged,
                ChangeSummary = model.ChangeSummary,
                IpAddress = model.IpAddress,
                UserAgent = model.UserAgent,
                CorrelationId = model.CorrelationId,
                IsSuccess = model.IsSuccess,
                ErrorMessage = model.ErrorMessage,
                Hash = model.Hash
            };
        }

        public static AuditLog ToEntity(this AuditLogDto model)
        {
            return new AuditLog
            {
                Id = model.Id.Equals(Guid.Empty) ? Guid.CreateVersion7() : model.Id,
                EntityName = model.EntityName,
                EntityId = model.EntityId,
                Action = model.Action,
                UserId = model.UserId,
                UserName = model.UserName,
                UserGroup = model.UserGroup,
                Timestamp = model.Timestamp,
                OldValues = model.OldValues,
                NewValues = model.NewValues,
                ChangedColumns = model.ChangedColumns,
                IsChanged = model.IsChanged,
                ChangeSummary = model.ChangeSummary,
                IpAddress = model.IpAddress,
                UserAgent = model.UserAgent,
                CorrelationId = model.CorrelationId,
                IsSuccess = model.IsSuccess,
                ErrorMessage = model.ErrorMessage,
                Hash = model.Hash
            };
        }
    }
}