//------------------------------------------------------------------------------  
// <auto-generated>                                                               
// This code was generated by QuickCode.                                          
// Runtime Version:1.0                                                            
//                                                                                
// Changes to this file may cause incorrect behavior and will be lost if          
// the code is regenerated.                                                       
// </auto-generated>                                                              
//------------------------------------------------------------------------------  
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Dtos.Category;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Domain.Entities;
using QuickCode.MyecommerceDemo.ProductCatalogModule.Domain.Enums;

namespace QuickCode.MyecommerceDemo.ProductCatalogModule.Application.Mappings
{
    public static class CategoryMappings
    {
        public static List<CategoryDto> ToDto(this IEnumerable<Category> model)
        {
            return model.Select(u => u.ToDto()).ToList();
        }

        public static CategoryDto ToDto(this Category model)
        {
            return new CategoryDto
            {
                Id = model.Id,
                ParentCategoryId = model.ParentCategoryId,
                Name = model.Name,
                Slug = model.Slug,
                IsActive = model.IsActive
            };
        }

        public static Category ToEntity(this CategoryDto model)
        {
            return new Category
            {
                Id = model.Id,
                ParentCategoryId = model.ParentCategoryId,
                Name = model.Name,
                Slug = model.Slug,
                IsActive = model.IsActive
            };
        }
    }
}