SELECT P.[ID], P.[SKU], P.[NAME], P.[PRICE] 
FROM [PRODUCTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[CATEGORY_ID] = @PRM_PRODUCT_CATEGORY_ID 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 