SELECT P.[ID], P.[SKU], P.[NAME], P.[PRICE] 
FROM [PRODUCTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[IS_FEATURED] = @PRM_PRODUCT_IS_FEATURED 
	AND P.[STATUS] = @PRM_PRODUCT_STATUS 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 