SELECT P.[ID], P.[SKU], P.[NAME], P.[STOCK_QUANTITY] 
FROM [PRODUCTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[STOCK_QUANTITY] < '10' 
	AND P.[STATUS] = @PRM_PRODUCT_STATUS 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 