SELECT P.[ID], P.[NAME], P.[SKU], P.[PRICE], C.[NAME] AS CATEGORY_NAME,
	B.[NAME] AS BRAND_NAME 
FROM [PRODUCTS] P 
	INNER JOIN [CATEGORIES] C 
			ON P.[CATEGORY_ID] = C.[ID] 
	INNER JOIN [BRANDS] B 
			ON P.[BRAND_ID] = B.[ID] 
WHERE P.[IsDeleted] = 0 
	AND C.[IsDeleted] = 0 
	AND B.[IsDeleted] = 0 
	AND P.[CATEGORY_ID] = @PRM_PRODUCTS_CATEGORY_ID 
	AND C.[ID] = @PRM_CATEGORIES_ID 
	AND P.[BRAND_ID] = @PRM_PRODUCTS_BRAND_ID 
	AND B.[ID] = @PRM_BRANDS_ID 
ORDER BY P.[ID] 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 