SELECT P.[ID], P.[NAME], P.[SKU], P.[CREATED_DATE] 
FROM [PRODUCTS] P 
WHERE P.[IsDeleted] = 0 
	AND P.[CREATED_DATE] > DATEADD(DAY, -30,
	GETDATE()) 
ORDER BY P.[CREATED_DATE] DESC 
OFFSET @StartIndex ROWS FETCH NEXT @PageSize ROWS ONLY 